### ISSUE TITLE
precompiled jar for this binding and 2.1.0-SNAPSHOT

### ISSUE THREAD

**Issue by rdslw** [computerlyrik/openhab2-addon-hs110#1]
As to have full maven/java compilation environment, it's necessary to install exactly 188 additional packages (apt-get doesn't lie ;) ) it's sometimes difficult.

Would it be possible for you to provide compiled binding to a jar file which maybe then placed under /usr/share/openhab2/addons/ directory?

That would be helpful for users.

**Comment by computerlyrik** [comment]
I have no clue yet how to do this, but i will provide a JAR in Releases as soon as possible

**Comment by computerlyrik** [comment]
closed by https://github.com/computerlyrik/openhab2-addon-hs110/releases/tag/v0.0.2
