### ISSUE TITLE
wrong decryption key

### ISSUE THREAD

**Issue by timtasse** [computerlyrik/openhab2-addon-hs110#3]
hi,

i have now a HS100 and use your code to control it.
your decryption key is incorrect, the correct one is 171,
then you not need the hack with the substring in the return statement.
important is java read the bytes as signed bytes, so an Byte.toUnsignedInt is needed before the XOR.
here my example:
```
public static final int DECRYPTION_KEY = 171;
final ByteBuffer dataBuffer = ByteBuffer.wrap(byteArray, 4, byteArray.length - 4);
final StringBuilder stringBuilder = new StringBuilder();
key = DECRYPTION_KEY;
        while(dataBuffer.hasRemaining()) {
            final int b = Byte.toUnsignedInt(dataBuffer.get());
            int in = b ^ key;
            stringBuilder.append((char) in);
            key = b;
        }
```
the result of this is a correct JSON und can directly used by a JsonParser.

cheers

**Comment by computerlyrik** [comment]
Closed in favor of https://github.com/openhab/openhab2-addons/pull/2348 - new rewritten Plugin, new Author
