### ISSUE TITLE
Reworked version of this addon

### ISSUE THREAD

**Issue by Hilbrand** [computerlyrik/openhab2-addon-hs110#5]
I was looking for a TP-Link addon and found your implementation. Since it was very specific written from the HS110 point of view and needed some rework I rewrote more of your code into a new addon. 
You can find the code in the branch `tp-link` in my fork: https://github.com/Hilbrand/openhab2-addons/tree/tp-link I've also created a new pull request https://github.com/openhab/openhab2-addons/pull/2348
But this means there are 2 pull request at the moment and so they've asked to sort this out.  Can you take a look at my code and see what you think of it? And how you would like to continue?

**Comment by computerlyrik** [comment]
Hi @Hilbrand!

I will be a little short in time in the near future. You are welcome to extend the work and maintain and merge your version of the addon into the openhab codebase.

Had a quick look at it - looks good!

Please keep me in the list of authors, if you used any of my work directly or as an inspiration.

If you agree to this, https://github.com/openhab/openhab2-addons/pull/2018 can be closed in favor of 
https://github.com/openhab/openhab2-addons/pull/2348

Thank you!

**Comment by Hilbrand** [comment]
Sounds good. 
Your name is in the binding.xml, in author tag, that will show up when showing general information about the addon, and in all source files that I've used as base I've put your name in the @author tag. I'll also can add you in the commit (I've created a single commit) In the signoff. This will look as follows:
`Also-by: Christian Fischer <your-email> (github: computerlyrik)`. In that case the convention requires an e-mail address. So if you also want that you need to provide me with your e-mail address.

Will that work for you?

**Comment by Hilbrand** [comment]
Hi @computerlyrik,

Can you confirm the author suggestions, and specific the commit comment related to the `Also-by`. If you also want this I needs an e-mail address.

Thanks.

**Comment by computerlyrik** [comment]
Hil @Hilbrand!

Allright, this would be sw-dev@computerlyrik.de

Thank you!

**Comment by Hilbrand** [comment]
Hi @computerlyrik,

I've added you to the commit message. And hereby close the issue.
